version: '3.9'

services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'

  backend:
    build:
      context: ./backend
    ports:
      - '5000:5000'
    env_file:
      - .env.docker
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:80'
    env_file:
      - .env.docker
    depends_on:
      - backend

volumes:
  mongo-data:
